"""CLIP ViT-L/14 zero-shot AI-video detector.

Strategy (from Liu et al. 2025 ablation tables):
  1. Embed N video frames via CLIP image encoder → (N, D)
  2. Embed a pair of text prompts via CLIP text encoder:
     - pos: "a video generated by an AI model"
     - neg: "a real video recorded by a camera"
  3. For each frame, compute cosine similarity to both prompts
  4. Softmax → AI-probability per frame → mean across frames

This is a training-free baseline. Expected M0 AUROC: ~55-65% (paper says
the best zero-shot AUROC on hyper-realistic clips is 22-23%, but our
pipeline includes lower-quality clips too).
"""

from __future__ import annotations

import logging

import numpy as np
import torch

from server.detection.base import BaseDetector
from server.detection.registry import register_detector

logger = logging.getLogger(__name__)


@register_detector("clip_zero_shot")
class CLIPZeroShot(BaseDetector):
    name = "clip_zero_shot"
    expects_frames = 8

    POS_PROMPTS = [
        "a video generated by an AI model",
        "an AI-generated synthetic video",
        "computer-generated video content",
    ]
    NEG_PROMPTS = [
        "a real video recorded by a camera",
        "an authentic human-captured video",
        "natural footage of real events",
    ]

    def __init__(
        self,
        device: str = "cuda",
        model_name: str = "ViT-L-14",
        pretrained: str = "openai",
        **kwargs,
    ) -> None:
        import open_clip

        self.device = device if torch.cuda.is_available() else "cpu"
        logger.info("CLIPZeroShot: loading %s/%s on %s", model_name, pretrained, self.device)

        self.model, _, self.preprocess = open_clip.create_model_and_transforms(
            model_name, pretrained=pretrained, device=self.device
        )
        self.model.eval()
        self.tokenizer = open_clip.get_tokenizer(model_name)

        # Pre-compute text embeddings (pos/neg prompt banks)
        with torch.no_grad():
            pos_tokens = self.tokenizer(self.POS_PROMPTS).to(self.device)
            neg_tokens = self.tokenizer(self.NEG_PROMPTS).to(self.device)
            pos_emb = self.model.encode_text(pos_tokens)
            neg_emb = self.model.encode_text(neg_tokens)
            pos_emb = pos_emb / pos_emb.norm(dim=-1, keepdim=True)
            neg_emb = neg_emb / neg_emb.norm(dim=-1, keepdim=True)
            # Average the prompt bank for robustness
            self.pos_emb = pos_emb.mean(dim=0, keepdim=True)
            self.neg_emb = neg_emb.mean(dim=0, keepdim=True)
            self.pos_emb /= self.pos_emb.norm()
            self.neg_emb /= self.neg_emb.norm()

    def predict(self, frames: np.ndarray) -> float:
        """frames: (T, H, W, 3) uint8. Returns AI-prob in [0, 1]."""
        from PIL import Image

        imgs = [Image.fromarray(frames[i]) for i in range(frames.shape[0])]
        batch = torch.stack([self.preprocess(img) for img in imgs]).to(self.device)

        with torch.no_grad():
            img_emb = self.model.encode_image(batch)
            img_emb = img_emb / img_emb.norm(dim=-1, keepdim=True)

            # Cosine similarity to pos and neg prompt banks
            sim_pos = (img_emb @ self.pos_emb.T).squeeze(-1)  # (T,)
            sim_neg = (img_emb @ self.neg_emb.T).squeeze(-1)

            # Softmax with temperature
            logits = torch.stack([sim_neg, sim_pos], dim=-1) * 100  # (T, 2)
            probs = logits.softmax(dim=-1)  # (T, 2) — [:, 1] is AI-prob
            ai_prob = probs[:, 1].mean().item()

        return float(ai_prob)

    def close(self) -> None:
        del self.model, self.pos_emb, self.neg_emb
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
