"""GPT-4o vision detector — sends 8 frames to OpenAI multimodal chat and
parses an AI-probability score from a structured JSON response.

Cost note: ~$0.01-0.02 per 8-frame video at 224x224 (input image tokens
dominate). For 1999 test videos ≈ $20-40.

Requires OPENAI_API_KEY in env. Uses the new chat.completions API with
JSON mode for robust score parsing.
"""

from __future__ import annotations

import base64
import io
import json
import logging
import os
import time

import numpy as np
from PIL import Image

from server.detection.base import BaseDetector
from server.detection.registry import register_detector

logger = logging.getLogger(__name__)

DEFAULT_MODEL = "gpt-4o-mini"  # 4o-mini ~10x cheaper than full 4o; swap to "gpt-4o" for paper
PROMPT = (
    "You are an expert at detecting AI-generated videos. I will show you 8 "
    "uniformly-sampled frames from a single short video clip. Your job is to "
    "judge whether the clip was generated by a video model (e.g. Sora, Pika, "
    "Runway, Veo, Vidu, Kling, Luma, Hunyuan, Wan) or recorded by a real "
    "camera.\n\nLook for: physically impossible motion, inconsistent textures "
    "across frames, melting / morphing objects, weirdly smooth or plastic "
    "skin, broken hands or limbs, impossible reflections, watermarks, text "
    "that drifts. Real videos may have noise, shaky camera, motion blur — "
    "those are NOT AI signs.\n\nReply with a single JSON object: "
    '{"ai_probability": <0.0-1.0>, "reason": "<one short sentence>"}.'
)


@register_detector("gpt4o_vision")
class GPT4oVision(BaseDetector):
    name = "gpt4o_vision"
    expects_frames = 8

    def __init__(
        self,
        device: str = "cpu",
        model: str = DEFAULT_MODEL,
        api_key: str | None = None,
        max_retries: int = 4,
        retry_base: float = 2.0,
        timeout: float = 60.0,
        **kwargs,
    ) -> None:
        from openai import OpenAI

        key = api_key or os.environ.get("OPENAI_API_KEY", "").strip()
        if not key:
            raise RuntimeError("OPENAI_API_KEY not set")
        self.client = OpenAI(api_key=key, timeout=timeout)
        self.model = model
        self.max_retries = max_retries
        self.retry_base = retry_base
        logger.info("GPT4oVision: model=%s", self.model)

    @staticmethod
    def _frames_to_data_urls(frames: np.ndarray) -> list[str]:
        urls = []
        for i in range(frames.shape[0]):
            img = Image.fromarray(frames[i])
            buf = io.BytesIO()
            img.save(buf, format="JPEG", quality=80)
            b64 = base64.b64encode(buf.getvalue()).decode()
            urls.append(f"data:image/jpeg;base64,{b64}")
        return urls

    def predict(self, frames: np.ndarray) -> float:
        urls = self._frames_to_data_urls(frames)
        content = [{"type": "text", "text": PROMPT}]
        for url in urls:
            content.append({"type": "image_url",
                           "image_url": {"url": url, "detail": "low"}})

        last_err = None
        for attempt in range(self.max_retries):
            try:
                resp = self.client.chat.completions.create(
                    model=self.model,
                    messages=[{"role": "user", "content": content}],
                    response_format={"type": "json_object"},
                    max_tokens=120,
                    temperature=0,
                )
                text = resp.choices[0].message.content or "{}"
                obj = json.loads(text)
                p = float(obj.get("ai_probability", 0.5))
                return max(0.0, min(1.0, p))
            except Exception as e:
                last_err = e
                wait = self.retry_base ** attempt
                logger.warning("gpt4o err (try %d): %s — sleep %.1fs", attempt + 1, e, wait)
                time.sleep(wait)
        raise RuntimeError(f"GPT-4o failed after {self.max_retries} retries: {last_err}")

    def close(self) -> None:
        pass
