import html
import logging
import time
from typing import Iterator

import requests

from server.crawler._generator import extract_generator as _extract_generator
from server.crawler.base import BaseCrawler, CrawledVideo
from server.crawler.registry import register

logger = logging.getLogger(__name__)

# AI-indicator keywords (English-centric for Reddit). These are *recall* hints
# used to decide whether a post is about AI video at all; canonical model-name
# extraction lives in server.crawler._generator.
_AI_KEYWORDS = [
    "ai generated",
    "ai-generated",
    "ai generated video",
    "generated by ai",
    "created with ai",
    "made with sora",
    "made with kling",
    "made with runway",
    "made with pika",
    "made with luma",
    "made with minimax",
    "made with hailuo",
    "made with veo",
    "sora generated",
    "kling generated",
    "text to video",
    "text-to-video",
    "t2v",
    "ai video",
    "aigc",
    "#sora",
    "#kling",
    "#runway",
    "#pika",
    "#aivideo",
    "#aiart",
]

_HEADERS = {
    "User-Agent": "RollingForge/0.1 (research crawler)",
}

# Domains whose URLs are likely to be downloadable videos via yt-dlp.
_VIDEO_DOMAINS = {
    "youtube.com", "www.youtube.com", "youtu.be",
    "bilibili.com", "www.bilibili.com",
    "v.redd.it",
    "vimeo.com", "www.vimeo.com",
    "streamable.com", "www.streamable.com",
    "tiktok.com", "www.tiktok.com",
    "twitter.com", "x.com",
}


def _has_ai_keywords(text: str) -> bool:
    """Check whether any AI-indicator keyword appears in *text*."""
    lower = text.lower()
    return any(kw in lower for kw in _AI_KEYWORDS)


def _is_video_url(url: str) -> bool:
    """Heuristic check: does this URL point to a video host or a video file?"""
    if not url:
        return False
    lower = url.lower()
    # Direct video file extensions
    if any(lower.endswith(ext) for ext in (".mp4", ".webm", ".mov", ".avi", ".mkv")):
        return True
    # Known video hosting domains
    for domain in _VIDEO_DOMAINS:
        if domain in lower:
            return True
    return False


def _extract_domain(url: str) -> str:
    """Extract the domain from a URL, e.g. 'www.youtube.com'."""
    try:
        # Simple extraction without urllib to keep it lightweight
        after_scheme = url.split("://", 1)[-1]
        return after_scheme.split("/", 1)[0].split("?", 1)[0].lower()
    except Exception:
        return ""


# Subreddits where *every* video post is assumed to be AI-generated.
# Posting on these subs = community norm is AI content, so we skip the
# keyword gate and treat them as platform-level AI tags. Extend via
# `crawl.platforms.reddit.ai_subreddits` in pipeline.yaml to add more
# without code edits.
_DEFAULT_AI_SUBREDDITS = [
    "aivideo",
    "sora",
    "kling",           # Kling / KlingAI discussion
    "runwayml",        # Runway Gen-3/4 official sub
    "pikalabs",        # Pika Labs community
    "lumalabs",        # Luma Dream Machine
    "StableVideoAI",   # Stable Video Diffusion community
    "hailuo_ai",       # MiniMax Hailuo
    "AIVideoCreation",
    "AIVIDEO",         # variant casing
]


@register("reddit")
class RedditCrawler(BaseCrawler):
    """Crawl Reddit AI-video subreddits for video candidates via the public JSON API."""

    name = "reddit"
    tier = 2

    def crawl(self, config: dict) -> Iterator[CrawledVideo]:
        subreddits: list[str] = config.get("subreddits", _DEFAULT_AI_SUBREDDITS)
        # Subreddits where posts auto-count as AI-generated (no keyword gate).
        # Defaults to the full crawled list so every crawled sub is trusted
        # unless explicitly overridden.
        ai_subreddits_cfg: list[str] = config.get("ai_subreddits", subreddits)
        ai_subreddit_set: set[str] = {s.lower() for s in ai_subreddits_cfg}
        search_queries: list[str] = config.get("search_queries", [
            "ai generated video",
            "text to video",
            "sora 2 video",
            "veo 3 video",
            "kling 2.1 video",
            "runway gen-4",
        ])
        max_videos: int = config.get("max_videos", 50)
        min_duration: float = config.get("min_duration", 0)
        max_duration: float = config.get("max_duration", 300)
        # Modern generative AI video (Sora/Veo/Kling/Runway/Pika/...) is a
        # post-2023 phenomenon. Older posts from AI-adjacent subs are almost
        # always something else: deepfake face-swaps, style-transfer filters
        # ("cartoonization AI"), academic demo reels, or news clips about
        # AI — categorically different from the text-to-video class the
        # benchmark targets. Default cutoff: 2023-01-01 UTC. Override via
        # config.published_after (YYYY-MM-DD) or set to null to disable.
        published_after_cfg = config.get("published_after", "2023-01-01")
        published_after_ts: float | None = None
        if published_after_cfg:
            import datetime as _dt
            published_after_ts = _dt.datetime.fromisoformat(
                f"{published_after_cfg}T00:00:00+00:00"
            ).timestamp()

        if not subreddits:
            logger.warning("RedditCrawler: no subreddits provided, nothing to crawl")
            return

        seen_ids: set[str] = set()
        yielded = 0

        # Phase 1: Fetch new (pubdate-sorted) posts from each subreddit.
        # Use `/new.json` instead of `/hot.json` — for a living benchmark
        # we care about fresh uploads more than community engagement. hot
        # can still show month-old posts dominating the top.
        for subreddit in subreddits:
            if yielded >= max_videos:
                break

            logger.info("RedditCrawler: fetching new posts from r/%s", subreddit)
            posts = self._fetch_listing(
                f"https://www.reddit.com/r/{subreddit}/new.json",
                params={"limit": 100},
            )

            for post in posts:
                if yielded >= max_videos:
                    break
                video = self._process_post(
                    post, seen_ids, min_duration, max_duration,
                    ai_subreddit_set, published_after_ts,
                )
                if video is not None:
                    yield video
                    yielded += 1

            time.sleep(2)

        # Phase 2: Search each subreddit with targeted queries (model-name heavy).
        # This only fires if Phase 1 hasn't already saturated max_videos —
        # for whitelisted AI subs `/new` alone usually fills the quota.
        for subreddit in subreddits:
            if yielded >= max_videos:
                break

            for query in search_queries:
                if yielded >= max_videos:
                    break

                logger.info("RedditCrawler: searching r/%s for '%s'", subreddit, query)
                posts = self._fetch_listing(
                    f"https://www.reddit.com/r/{subreddit}/search.json",
                    params={
                        "q": query,
                        "sort": "new",
                        "restrict_sr": "on",
                        "limit": 100,
                    },
                )

                for post in posts:
                    if yielded >= max_videos:
                        break
                    video = self._process_post(
                        post, seen_ids, min_duration, max_duration, ai_subreddit_set
                    )
                    if video is not None:
                        yield video
                        yielded += 1

                time.sleep(2)

        logger.info("RedditCrawler: yielded %d videos total", yielded)

    def estimate_available(self, config: dict) -> int:
        """Rough upper-bound based on config."""
        subreddits = config.get("subreddits", ["aivideo"])
        search_queries = config.get("search_queries", ["ai generated video"])
        max_videos = config.get("max_videos", 50)
        # Hot listing (up to 100) + one search per query per subreddit (up to 100 each)
        per_sub = 100 + len(search_queries) * 100
        return min(len(subreddits) * per_sub, max_videos)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _fetch_listing(url: str, params: dict | None = None) -> list[dict]:
        """Fetch a Reddit JSON listing and return the list of post data dicts."""
        try:
            resp = requests.get(url, params=params, headers=_HEADERS, timeout=15)
            resp.raise_for_status()
            body = resp.json()
        except requests.RequestException:
            logger.warning("RedditCrawler: request failed for %s", url, exc_info=True)
            return []
        except ValueError:
            logger.warning("RedditCrawler: invalid JSON from %s", url)
            return []

        children = body.get("data", {}).get("children", [])
        return [child.get("data", {}) for child in children if child.get("data")]

    def _process_post(
        self,
        post: dict,
        seen_ids: set[str],
        min_duration: float,
        max_duration: float,
        ai_subreddit_set: set[str],
        published_after_ts: float | None,
    ) -> CrawledVideo | None:
        """Convert a Reddit post to a CrawledVideo, or None if unsuitable."""
        post_id = post.get("id", "")
        if not post_id or post_id in seen_ids:
            return None

        # Pre-filter by publication date before doing video URL extraction —
        # cheaper than running the AI-keyword gate on pre-2023 noise.
        if published_after_ts is not None:
            created_utc = post.get("created_utc")
            if created_utc and float(created_utc) < published_after_ts:
                logger.debug("Skipping reddit post %s: pre-cutoff (%s)", post_id, created_utc)
                return None

        # Determine if this post has a video and extract the download URL
        download_url = self._extract_video_url(post)
        if not download_url:
            return None

        seen_ids.add(post_id)

        title: str = post.get("title", "")
        selftext: str = post.get("selftext", "")
        flair: str = post.get("link_flair_text", "") or ""
        subreddit: str = post.get("subreddit", "")

        combined_text = f"{title} {selftext} {flair}"

        # Whitelisted subs = every video post is assumed AI-generated (community
        # norm); outside the whitelist we still require a keyword hit. This is
        # the "L3 white-list" pass from the crawl funnel design — zero cost,
        # ~90% precision on the whitelisted subs.
        is_ai_subreddit = subreddit.lower() in ai_subreddit_set
        has_keyword = _has_ai_keywords(combined_text)

        if not is_ai_subreddit and not has_keyword:
            logger.debug("Skipping reddit post %s (%s): no AI indicators", post_id, title[:60])
            return None

        # Check duration for Reddit-hosted videos
        duration = None
        media = post.get("media") or {}
        reddit_video = media.get("reddit_video") or {}
        if reddit_video:
            duration_raw = reddit_video.get("duration")
            if duration_raw is not None:
                try:
                    duration = float(duration_raw)
                except (ValueError, TypeError):
                    pass

        if duration is not None:
            if duration < min_duration or duration > max_duration:
                return None

        claimed_generator = _extract_generator(combined_text)

        # Label source: whitelisted subs get a tier2_channel_whitelist tag
        # (community-level trust), keyword-matched posts from other subs get
        # tier2_platform_tag (weaker signal but still platform-bounded).
        label_source = "tier2_channel_whitelist" if is_ai_subreddit else "tier2_platform_tag"

        created_utc = post.get("created_utc")
        published_at = None
        if created_utc:
            try:
                import datetime
                published_at = datetime.datetime.fromtimestamp(
                    float(created_utc), tz=datetime.timezone.utc
                ).isoformat()
            except (ValueError, TypeError, OSError):
                pass

        content_tags = []
        if flair:
            content_tags.append(flair)
        if subreddit:
            content_tags.append(f"r/{subreddit}")

        permalink = post.get("permalink", "")
        reddit_page_url = (
            f"https://www.reddit.com{permalink}" if permalink
            else f"https://www.reddit.com/r/{subreddit}/comments/{post_id}"
        )
        # source_url: if the download URL is a direct v.redd.it mp4, use it —
        # VideoEmbed's smart-default branch will render an HTML5 <video> for
        # it without any platform-specific case. Otherwise keep the reddit
        # page URL as a "view on platform" fallback.
        if download_url and ".mp4" in download_url:
            source_url = download_url
        else:
            source_url = reddit_page_url

        # Thumbnail resolution priority:
        #   1. `preview.images[0].source.url` — higher-res, always a real URL
        #      when it exists. Reddit returns these for both image and video
        #      posts (video posts get a static poster frame).
        #   2. `post.thumbnail` — fallback to the small square preview, but
        #      only if it starts with `http` (the field is often "self",
        #      "default", "nsfw", "spoiler" for non-image posts).
        # In BOTH cases we must `html.unescape()` because Reddit returns URLs
        # with `&amp;` query separators that break direct fetches.
        thumbnail_url: str | None = None
        preview = post.get("preview") or {}
        preview_imgs = preview.get("images") or []
        if preview_imgs:
            src_url = (preview_imgs[0].get("source") or {}).get("url")
            if src_url:
                thumbnail_url = html.unescape(src_url)
        if thumbnail_url is None:
            raw_thumb = post.get("thumbnail", "")
            if isinstance(raw_thumb, str) and raw_thumb.startswith("http"):
                thumbnail_url = html.unescape(raw_thumb)

        return CrawledVideo(
            source_platform="reddit",
            source_url=source_url,
            source_id=post_id,
            label="fake",
            label_source=label_source,
            title=title,
            claimed_generator=claimed_generator,
            content_tags=content_tags,
            published_at=published_at,
            raw_metadata=post,
            video_bytes=None,
            download_url=download_url,
            thumbnail_url=thumbnail_url,
            duration_sec=duration,
            resolution_w=int(reddit_video["width"]) if reddit_video.get("width") else None,
            resolution_h=int(reddit_video["height"]) if reddit_video.get("height") else None,
            fps=None,
        )

    @staticmethod
    def _extract_video_url(post: dict) -> str | None:
        """
        Determine the downloadable video URL from a Reddit post.

        Preference order:
        1. Reddit-hosted video `fallback_url` — direct CMAF_*.mp4 on
           v.redd.it. HTML5 `<video>` plays it inline via the VideoEmbed
           smart-default branch (no iframe, no DASH player needed). Hotlink
           is open (no Referer check).
        2. Crosspost fallback_url — same treatment for reposted videos.
        3. External video URLs (v.youtube.com, vimeo, etc.) — legacy path.
        4. Fall back to the Reddit permalink as a last resort so the detail
           page can at least show "Open on Reddit".

        Returns None if the post has no video at all.
        """
        media = post.get("media") or {}
        reddit_video = media.get("reddit_video") or {}
        fallback = reddit_video.get("fallback_url")
        if fallback:
            # Strip the `?source=fallback` suffix — our isDirectVideoUrl
            # regex on the frontend tolerates it, but a clean URL makes
            # the downstream caching and dedup behavior predictable.
            return fallback

        # Crosspost case — pull fallback_url from the parent post.
        crosspost_list = post.get("crosspost_parent_list") or []
        for xpost in crosspost_list:
            xmedia = xpost.get("media") or {}
            xvideo = xmedia.get("reddit_video") or {}
            xfallback = xvideo.get("fallback_url")
            if xfallback:
                return xfallback
            xurl = xpost.get("url", "")
            if xurl and _is_video_url(xurl):
                return xurl

        # External video hosters (YouTube/Vimeo/etc) linked from a Reddit post.
        url = post.get("url", "")
        if url and _is_video_url(url):
            return url

        # Nothing playable.
        return None
