import logging
from typing import Iterator

import yt_dlp

from server.crawler._generator import extract_generator as _extract_generator
from server.crawler.base import BaseCrawler, CrawledVideo
from server.crawler.registry import register

logger = logging.getLogger(__name__)

# Keywords that indicate AI-generated content in video descriptions or titles.
# Recall hints only — canonical model-name extraction lives in
# server.crawler._generator.
_AI_KEYWORDS = [
    "ai generated",
    "ai-generated",
    "ai generated video",
    "generated by ai",
    "created with ai",
    "made with sora",
    "made with kling",
    "made with runway",
    "made with pika",
    "made with luma",
    "made with minimax",
    "made with hailuo",
    "made with veo",
    "sora generated",
    "kling generated",
    "text to video",
    "text-to-video",
    "aigc",
    "ai创作",
    "ai生成",
    "#aiart",
    "#aivideo",
    "#sora",
    "#kling",
    "#runway",
]


def _has_ai_disclosure(info: dict) -> bool:
    """Check whether YouTube's own AI-generated label is present."""
    return bool(info.get("is_generated_content"))


def _has_ai_keywords(text: str) -> bool:
    """Check whether any AI-indicator keyword appears in *text*."""
    lower = text.lower()
    return any(kw in lower for kw in _AI_KEYWORDS)


def _walk_entries(node: dict):
    """Yield leaf video entries from a nested yt-dlp info tree.

    Channel extractions return a tree like channel → {Videos, Shorts, Live}
    tabs → actual video entries. Flat search returns a single-level entries
    list. This helper handles both so the caller can stay generic.
    """
    entries = node.get("entries")
    if entries is None:
        # Leaf: must be an actual video entry with an id.
        if node.get("id") and node.get("_type", "video") != "playlist":
            yield node
        return
    for entry in entries:
        if entry is None:
            continue
        # Recurse if this is a nested playlist / tab / channel node.
        if entry.get("_type") in {"playlist", "url"} and "entries" in entry:
            yield from _walk_entries(entry)
        else:
            yield entry


@register("youtube")
class YouTubeCrawler(BaseCrawler):
    """Crawl YouTube for AI-generated video candidates using yt-dlp.

    Two ingestion modes, both feeding the same Phase-2 metadata pipeline:

    - **Keyword search** (`search_queries`): classic `ytsearch<N>:<query>`
      mode. Each result must also pass the AI-keyword gate on its title.

    - **Channel whitelist** (`channels`): latest uploads from a curated
      list of known AI-video creator / vendor channels. These bypass the
      keyword gate entirely — the channel itself is the AI signal. This
      is the "L3 white-list" pass from the crawl funnel design and is
      what keeps a living benchmark fed with fresh content for free (no
      YouTube API quota, no rate limiting surprises).
    """

    name = "youtube"
    tier = 2

    def crawl(self, config: dict) -> Iterator[CrawledVideo]:
        search_queries: list[str] = config.get("search_queries", [])
        channels: list[str] = config.get("channels", [])
        channel_video_limit: int = config.get("channel_video_limit", 15)
        max_videos: int = config.get("max_videos", 50)
        min_duration: float = config.get("min_duration", 0)
        max_duration: float = config.get("max_duration", 300)
        # Channel-whitelisted entries get a more permissive duration window
        # (default 300s) — known AI creators post 1-5 minute showcases and
        # short films that are legitimate raw AI output, just longer than
        # the keyword-search tier's 60s cap. Keyword search still uses
        # `max_duration` because the 60s cap is how we keep out tutorials
        # and reaction content from untrusted search hits.
        channel_max_duration: float = config.get("channel_max_duration", 300)

        if not search_queries and not channels:
            logger.warning(
                "YouTubeCrawler: no search_queries or channels provided, nothing to crawl"
            )
            return

        # Search more than needed since most results won't pass the AI filter.
        # Guarded against empty search_queries for channels-only mode.
        per_query = (
            max(10, (max_videos * 5) // len(search_queries)) if search_queries else 0
        )
        seen_ids: set[str] = set()
        yielded = 0

        # YouTube's web/ios player_client triggers a "Sign in to confirm
        # you're not a bot" challenge on most recent uploads since late 2024,
        # killing yt-dlp full-metadata fetches. The android client is a known
        # workaround that still returns metadata (DRM blocks playback streams,
        # but we only need title/duration/resolution/thumbnail). Verified
        # 2026-04-12 against MattVidPro / CuriousRefuge channel uploads that
        # were 100% bot-walled on web client.
        flat_opts = {
            "quiet": True,
            "no_warnings": True,
            "extract_flat": True,
            "ignoreerrors": True,
            "extractor_args": {"youtube": {"player_client": ["android"]}},
        }

        # (url, is_whitelisted_channel, channel_label) — the whitelist flag
        # tells Phase 2 to skip the AI-keyword gate for channel-sourced URLs.
        candidate_urls: list[tuple[str, bool, str | None]] = []

        # Channel-sourced entries skip Phase 2 entirely — they're yielded
        # from the flat-search metadata directly. Rationale: YouTube's
        # anti-bot aggressively blocks yt-dlp full-metadata fetches
        # ("Sign in to confirm you're not a bot"), so Phase 2 dies on
        # ~90% of channel entries. The flat search already has enough
        # to construct a CrawledVideo (id, title, duration, thumbnail,
        # description, channel). For whitelisted channels we trust the
        # channel itself as the AI signal — we don't need the richer
        # Phase-2 metadata to confirm.
        channel_videos: list[CrawledVideo] = []

        # Phase 1a — keyword search
        for query in search_queries:
            search_url = f"ytsearch{per_query}:{query}"
            logger.info("YouTubeCrawler: searching '%s' (up to %d)", query, per_query)

            try:
                with yt_dlp.YoutubeDL(flat_opts) as ydl:
                    result = ydl.extract_info(search_url, download=False)
            except Exception:
                logger.warning("YouTubeCrawler: search failed for '%s'", query, exc_info=True)
                continue

            if result is None:
                continue

            for entry in result.get("entries") or []:
                if entry is None:
                    continue
                vid = entry.get("id") or entry.get("url", "")
                title = entry.get("title", "")
                if vid and vid not in seen_ids:
                    # Quick title-based pre-filter
                    if _has_ai_keywords(title.lower()):
                        seen_ids.add(vid)
                        url = entry.get("url") or f"https://www.youtube.com/watch?v={vid}"
                        candidate_urls.append((url, False, None))
                        logger.debug("Candidate (title match): %s — %s", vid, title[:60])
                    else:
                        logger.debug("Skipped (no title match): %s — %s", vid, title[:60])

        # Phase 1b — whitelisted channel latest uploads.
        # Channel URLs can be any form yt-dlp accepts:
        #   https://www.youtube.com/@CuriousRefuge/videos
        #   https://www.youtube.com/channel/UCxxxx/videos
        # The `playlistend` option caps the number of recent uploads yt-dlp
        # walks per channel, so we don't pull a creator's entire back-catalog
        # every run.
        channel_opts = {**flat_opts, "playlistend": channel_video_limit}
        for channel_url in channels:
            logger.info(
                "YouTubeCrawler: fetching %d latest uploads from %s",
                channel_video_limit, channel_url,
            )
            try:
                with yt_dlp.YoutubeDL(channel_opts) as ydl:
                    result = ydl.extract_info(channel_url, download=False)
            except Exception:
                logger.warning(
                    "YouTubeCrawler: channel fetch failed for %s",
                    channel_url,
                    exc_info=True,
                )
                continue

            if result is None:
                continue

            # Channel listings can nest: channel → tabs → videos. Walk both.
            entries = list(_walk_entries(result))
            logger.info(
                "YouTubeCrawler: %s yielded %d raw entries", channel_url, len(entries),
            )

            for entry in entries:
                if entry is None:
                    continue
                vid = entry.get("id") or entry.get("url", "")
                if not vid or vid in seen_ids:
                    continue
                seen_ids.add(vid)

                # Duration filter up-front — flat extract already includes
                # `duration` for channel listings. Saves us yielding 20+
                # minute tutorial videos that would be dropped downstream.
                dur = entry.get("duration")
                try:
                    dur_f = float(dur) if dur is not None else None
                except (TypeError, ValueError):
                    dur_f = None
                if dur_f is not None and (
                    dur_f < min_duration or dur_f > channel_max_duration
                ):
                    continue

                title = entry.get("title") or ""
                description = entry.get("description") or ""
                combined_text = f"{title} {description}"
                claimed_generator = _extract_generator(combined_text)

                # Thumbnail: use the canonical unsigned `hqdefault.jpg` form
                # instead of the signed URL from yt-dlp's flat-extract list.
                # The signed URLs expire; `i.ytimg.com/vi/<id>/hqdefault.jpg`
                # is stable forever, hotlink-friendly, and YouTube serves it
                # for every public video.
                thumbnail_url = f"https://i.ytimg.com/vi/{vid}/hqdefault.jpg"

                url = entry.get("url") or f"https://www.youtube.com/watch?v={vid}"
                channel_videos.append(
                    CrawledVideo(
                        source_platform="youtube",
                        source_url=url,
                        source_id=vid,
                        label="fake",
                        label_source="tier2_channel_whitelist",
                        title=title,
                        claimed_generator=claimed_generator,
                        content_tags=[f"channel:{channel_url}"],
                        published_at=None,
                        raw_metadata={},
                        download_url=url,
                        thumbnail_url=thumbnail_url,
                        duration_sec=dur_f,
                        resolution_w=None,
                        resolution_h=None,
                        fps=None,
                    )
                )

        logger.info(
            "YouTubeCrawler: %d channel-whitelist videos + %d keyword candidates",
            len(channel_videos), len(candidate_urls),
        )

        # Yield channel-whitelist videos first — they're already fully
        # formed, don't need Phase 2, and the anti-bot can't hit them.
        for v in channel_videos:
            if yielded >= max_videos:
                break
            yield v
            yielded += 1

        # Phase 2: full metadata extraction for candidates only.
        # Same player_client=android workaround as flat_opts above. Without
        # this, ~95% of recent uploads return "Sign in to confirm you're
        # not a bot" and the entire YouTube crawl yields zero from the
        # search-query path.
        full_opts = {
            "quiet": True,
            "no_warnings": True,
            "skip_download": True,
            "ignoreerrors": True,
            "extractor_args": {"youtube": {"player_client": ["android"]}},
        }

        # Bot-wall circuit breaker. Phase 2 hits the "Sign in to confirm
        # you're not a bot" wall whenever YouTube tightens its bot detection.
        # Three-tier safety net:
        #   1. consecutive_failures: bails after 5 in a row (catches a sudden
        #      onset where a previously-working client just got blocked).
        #   2. total_failures: bails after 50 cumulative failures across the
        #      whole Phase 2 loop (catches the case where successes are
        #      interspersed but the failure rate is still > 90%, which makes
        #      Phase 2 unviable).
        #   3. max_phase2_attempts: hard cap on Phase 2 candidate processing
        #      regardless of success/failure mix. The first ~50 keyword
        #      candidates are usually the highest-novelty hits; the rest
        #      have rapidly diminishing returns. Caps the total time the
        #      crawler can spend in Phase 2 to ~3-5 minutes wall-clock.
        # ANY trip stops Phase 2 immediately. Channel-walked rows from
        # Phase 1b are unaffected and get pushed when the runner finishes.
        consecutive_failures = 0
        total_failures = 0
        phase2_attempts = 0
        bot_wall_bailout_consecutive = 5
        bot_wall_bailout_total = 50
        max_phase2_attempts = 50

        for url, is_whitelisted, channel_label in candidate_urls:
            if yielded >= max_videos:
                break

            if consecutive_failures >= bot_wall_bailout_consecutive:
                logger.warning(
                    "YouTubeCrawler: Phase 2 hit %d consecutive failures, "
                    "bailing out (probable bot wall). Channel-walked rows "
                    "are unaffected.",
                    bot_wall_bailout_consecutive,
                )
                break
            if total_failures >= bot_wall_bailout_total:
                logger.warning(
                    "YouTubeCrawler: Phase 2 hit %d total failures, bailing "
                    "out (failure rate too high to be productive). Channel-"
                    "walked rows are unaffected.",
                    bot_wall_bailout_total,
                )
                break
            if phase2_attempts >= max_phase2_attempts:
                logger.info(
                    "YouTubeCrawler: Phase 2 hit hard cap of %d attempts, "
                    "stopping (diminishing returns past this point).",
                    max_phase2_attempts,
                )
                break
            phase2_attempts += 1

            try:
                with yt_dlp.YoutubeDL(full_opts) as ydl:
                    info = ydl.extract_info(url, download=False)
            except Exception:
                logger.debug("Failed to extract metadata for %s", url)
                consecutive_failures += 1
                total_failures += 1
                continue

            if info is None:
                consecutive_failures += 1
                total_failures += 1
                continue

            try:
                video = self._process_entry(
                    info, min_duration, max_duration, is_whitelisted, channel_label,
                )
            except Exception:
                logger.warning("Failed to process %s", url, exc_info=True)
                consecutive_failures += 1
                total_failures += 1
                continue

            if video is not None:
                yield video
                yielded += 1
                consecutive_failures = 0  # success resets the streak

        logger.info("YouTubeCrawler: yielded %d videos total", yielded)

    def estimate_available(self, config: dict) -> int:
        """Rough upper-bound across search queries + whitelisted channels."""
        queries = config.get("search_queries", [])
        channels = config.get("channels", [])
        channel_limit = config.get("channel_video_limit", 15)
        max_videos = config.get("max_videos", 50)
        estimate = len(queries) * 20 + len(channels) * channel_limit
        return min(estimate, max_videos)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _process_entry(
        info: dict,
        min_duration: float,
        max_duration: float,
        is_whitelisted: bool = False,
        channel_label: str | None = None,
    ) -> CrawledVideo | None:
        """Convert a yt-dlp info dict to a CrawledVideo, or None if unsuitable."""
        video_id: str = info.get("id", "")
        if not video_id:
            return None

        duration = info.get("duration") or 0
        if duration < min_duration or duration > max_duration:
            return None

        title: str = info.get("title", "")
        description: str = info.get("description", "")
        tags = info.get("tags") or []
        combined_text = f"{title} {description} {' '.join(str(t) for t in tags)}"

        has_platform_label = _has_ai_disclosure(info)
        has_keyword = _has_ai_keywords(combined_text)

        # Whitelisted channels bypass the AI-keyword gate. The channel
        # itself is the AI signal — requiring the creator to *also* put
        # "AI" in their title defeats the whole point of the whitelist.
        if not has_platform_label and not has_keyword and not is_whitelisted:
            logger.debug("Skipping %s (%s): no AI indicators", video_id, title[:60])
            return None

        if has_platform_label:
            label_source = "tier2_platform_tag"
        elif is_whitelisted:
            label_source = "tier2_channel_whitelist"
        else:
            label_source = "tier3_llm"

        claimed_generator = _extract_generator(combined_text)

        # Resolution from yt-dlp metadata is unreliable when using the
        # android player_client (the workaround for the late-2024 bot wall).
        # Android only exposes ~360p format streams, so info.width/height
        # would mis-report the source video's true resolution. Setting both
        # to None lets the QualityFilter skip its resolution check (it has
        # an explicit "both unknown → pass through" branch). True resolution
        # is recovered later when the inline download stage probes the mp4.
        width = None
        height = None
        fps = info.get("fps")

        source_url = info.get("webpage_url") or f"https://www.youtube.com/watch?v={video_id}"

        tags = info.get("tags") or []
        categories = info.get("categories") or []
        content_tags = [str(t) for t in tags + categories]
        if channel_label:
            content_tags.append(f"channel:{channel_label}")

        # yt-dlp returns YYYYMMDD (date only, no time). Convert to ISO date
        # format so the runner can parse consistently with other crawlers.
        raw_upload = info.get("upload_date")  # "YYYYMMDD" or None
        published_at = None
        if raw_upload and len(raw_upload) == 8:
            published_at = f"{raw_upload[:4]}-{raw_upload[4:6]}-{raw_upload[6:8]}"

        return CrawledVideo(
            source_platform="youtube",
            source_url=source_url,
            source_id=video_id,
            label="fake",
            label_source=label_source,
            title=title,
            claimed_generator=claimed_generator,
            content_tags=content_tags,
            published_at=published_at,
            raw_metadata=info,
            video_bytes=None,
            download_url=source_url,
            thumbnail_url=f"https://i.ytimg.com/vi/{video_id}/mqdefault.jpg",
            duration_sec=float(duration) if duration else None,
            resolution_w=int(width) if width else None,
            resolution_h=int(height) if height else None,
            fps=float(fps) if fps else None,
        )
